document.write('<nav class="nav"> ')
document.write('    <ul> ')
document.write('        <li> ')
document.write('            <a href="./Top.html">Top</a> ')
document.write('        </li> ')
document.write('        <li> ')
document.write('            <a href="./Manual.html">操作方法</a> ')
document.write('        </li> ')
document.write('        <li> ')
document.write('            <a href="./System.html">ゲームシステム</a> ')
document.write('        </li> ')
document.write('        <li> ')
document.write('            <a href="./Movie.html">プレイ動画</a> ')
document.write('        </li> ')
document.write('        <li> ')
document.write('            <a href="./SourceCode.html">ソースコード</a> ')
document.write('        </li> ')
document.write('    </ul> ')
document.write('</nav> ')